import jsPDF from "jspdf";

interface ExportData {
  cohesion:   number;
  phi:        number;
  confidence: number;
  soilLabel:  string;
  soilType:   string;
  testType:   string;
  inputs: {
    FC: string; WL: string; IP: string;
    MC: string; SR: string; ROD: string;
  };
  lang: "fr" | "en";
}

const labels = {
  fr: {
    title:       "Rapport d'Analyse Géotechnique",
    subtitle:    "GeoSmartX — Plateforme IA Géotechnique",
    date:        "Date",
    soil:        "Nature du sol",
    test:        "Type d'essai",
    params:      "Paramètres d'entrée",
    results:     "Résultats de l'analyse",
    cohesion:    "Cohésion (c)",
    phi:         "Angle de frottement (φ)",
    confidence:  "Indice de confiance",
    soilId:      "Nature identifiée",
    FC:  "Teneur en fines (FC)",
    WL:  "Limite de liquidité (WL)",
    IP:  "Indice de plasticité (IP)",
    MC:  "Teneur en eau (MC)",
    SR:  "Degré de saturation (SR)",
    ROD: "Degré d'altération (ROD)",
    footer:      "Généré par GeoSmartX · geosmart.dz · Alger, Algérie",
    disclaimer:  "Ce rapport est généré automatiquement à titre indicatif. Veuillez vérifier les résultats avec un ingénieur géotechnicien qualifié.",
    diagramTitle: "DIAGRAMME DE MOHR-COULOMB",
  },
  en: {
    title:       "Geotechnical Analysis Report",
    subtitle:    "GeoSmartX — Geotechnical AI Platform",
    date:        "Date",
    soil:        "Soil type",
    test:        "Test type",
    params:      "Input parameters",
    results:     "Analysis results",
    cohesion:    "Cohesion (c)",
    phi:         "Friction angle (φ)",
    confidence:  "Confidence index",
    soilId:      "Identified soil",
    FC:  "Fines content (FC)",
    WL:  "Liquid limit (WL)",
    IP:  "Plasticity index (IP)",
    MC:  "Water content (MC)",
    SR:  "Saturation degree (SR)",
    ROD: "Alteration degree (ROD)",
    footer:      "Generated by GeoSmartX · geosmart.dz · Algiers, Algeria",
    disclaimer:  "This report is automatically generated for informational purposes. Please verify results with a qualified geotechnical engineer.",
    diagramTitle: "MOHR-COULOMB DIAGRAM",
  },
};

// ── Draw a semicircle using bezier curves (upper half only) ──────────────────
// jsPDF has no native arc clipping, so we approximate upper semicircle
// with 2 cubic bezier curves (standard circle approximation k=0.5523)
function drawSemiCircle(
  doc: jsPDF,
  cx: number,   // center x in mm
  cy: number,   // center y (on axis) in mm  
  r: number,    // radius in mm
) {
  const k = 0.5523 * r;
  // Upper semicircle: left point -> top -> right point
  // left = (cx-r, cy), top = (cx, cy-r), right = (cx+r, cy)
  doc.lines(
    [
      // First quadrant: left to top
      [k, -r, r, -r, r, -r],  // won't work directly, need moveTo
    ],
    cx - r, cy,
    [1, 1],
    undefined,
    false
  );

  // Better approach: use bezier path manually
  // Move to left point, draw upper arc via 2 bezier segments
  const x0 = cx - r;
  const y0 = cy;
  const x1 = cx;
  const y1 = cy - r;
  const x2 = cx + r;
  const y2 = cy;

  // Left to top (first quadrant going counterclockwise = upper half)
  // Control points for quarter circle
  doc.lines(
    [
      [k,  0,    r, -(r - k), r,    -r],   // left -> top  
      [0, -k,    r - k + r - r, 0, r, r],  // this is wrong
    ],
    x0, y0, [1,1], undefined, false
  );
}

// Better: use canvas-like path with moveTo and bezierCurveTo
function drawUpperSemiCirclePath(
  doc: jsPDF,
  cx: number,
  cy: number,
  r: number,
  strokeColor: string,
  lineWidth: number
) {
  const k = 0.5523 * r; // bezier approximation constant

  const setColor = (hex: string) => {
    const rv = parseInt(hex.slice(1,3),16);
    const gv = parseInt(hex.slice(3,5),16);
    const bv = parseInt(hex.slice(5,7),16);
    doc.setDrawColor(rv, gv, bv);
  };

  setColor(strokeColor);
  doc.setLineWidth(lineWidth);

  // Draw upper semicircle as two bezier curves
  // Points: L=(cx-r,cy), T=(cx,cy-r), R=(cx+r,cy)
  // L->T: cp1=(cx-r, cy-k), cp2=(cx-k, cy-r)
  // T->R: cp1=(cx+k, cy-r), cp2=(cx+r, cy-k)
  doc.lines(
    [
      // each entry: [cp1x, cp1y, cp2x, cp2y, ex, ey] relative to current pos
      [0, -k,   k - r + r - k, -(r - k) - k,  r, -r],  // L to T
      [k,  0,   r, k - r,       r,  r],                  // T to R  
    ],
    cx - r, cy,
    [1, 1],
    undefined,
    false
  );
}

export async function exportPDF(data: ExportData): Promise<void> {
  const t = labels[data.lang];
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const W = 210;
  const margin = 18;
  const contentW = W - margin * 2;
  let y = 0;

  const rgb = (hex: string): [number, number, number] => [
    parseInt(hex.slice(1,3),16),
    parseInt(hex.slice(3,5),16),
    parseInt(hex.slice(5,7),16),
  ];

  const setFont = (size: number, style: "normal"|"bold" = "normal", color = "#0F1117") => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...rgb(color));
  };

  const fillRect = (x: number, y: number, w: number, h: number, fill: string, stroke = "#E2E8F0", radius = 0) => {
    doc.setFillColor(...rgb(fill));
    doc.setDrawColor(...rgb(stroke));
    doc.setLineWidth(0.3);
    if (radius > 0) doc.roundedRect(x, y, w, h, radius, radius, "FD");
    else doc.rect(x, y, w, h, "FD");
  };

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFillColor(...rgb("#0F1117"));
  doc.rect(0, 0, W, 42, "F");

  doc.setFillColor(...rgb("#6366F1"));
  doc.circle(margin + 6, 14, 6, "F");
  setFont(10, "bold", "#FFFFFF");
  doc.text("G", margin + 6, 14 + 3.5, { align: "center" });

  setFont(18, "bold", "#FFFFFF");
  doc.text("Geo", margin + 16, 16);
  setFont(18, "bold", "#6366F1");
  doc.text("SmartX", margin + 30, 16);
  setFont(10, "normal", "#94A3B8");
  doc.text(t.subtitle, margin + 16, 23);

  const now = new Date();
  const dateStr = now.toLocaleDateString(data.lang === "fr" ? "fr-FR" : "en-US", {
    year: "numeric", month: "long", day: "numeric",
  });
  setFont(8, "normal", "#64748B");
  doc.text(`${t.date}: ${dateStr}`, W - margin, 14, { align: "right" });

  setFont(14, "bold", "#FFFFFF");
  doc.text(t.title, margin + 16, 34);

  y = 52;

  // ── Context row ───────────────────────────────────────────────────────────
  const halfW = contentW / 2 - 3;
  fillRect(margin, y, halfW, 18, "#F8FAFC", "#E2E8F0", 2);
  fillRect(margin + halfW + 6, y, halfW, 18, "#F8FAFC", "#E2E8F0", 2);

  setFont(7, "bold", "#64748B");
  doc.text(t.soil.toUpperCase(), margin + 4, y + 6);
  setFont(10, "bold", "#0F1117");
  doc.text(data.soilLabel, margin + 4, y + 13);

  setFont(7, "bold", "#64748B");
  doc.text(t.test.toUpperCase(), margin + halfW + 10, y + 6);
  setFont(10, "bold", "#0F1117");
  doc.text(`Triaxial ${data.testType.toUpperCase()}`, margin + halfW + 10, y + 13);

  y += 26;

  // ── Result cards ──────────────────────────────────────────────────────────
  setFont(11, "bold", "#0F1117");
  doc.text(t.results, margin, y);
  y += 7;

  const cardW = (contentW - 9) / 4;
  const cards = [
    { label: t.cohesion,   value: `${data.cohesion} kPa`, color: "#10B981" },
    { label: t.phi,        value: `${data.phi}\xB0`,       color: "#F59E0B" },
    { label: t.confidence, value: `${data.confidence}%`,   color: "#6366F1" },
    { label: t.soilId,     value: data.soilLabel,           color: "#1E293B" },
  ];

  cards.forEach((card, i) => {
    const x = margin + i * (cardW + 3);
    fillRect(x, y, cardW, 22, "#F8FAFC", "#E2E8F0", 2);
    setFont(7, "normal", "#64748B");
    doc.text(card.label, x + 3, y + 7);
    doc.setTextColor(...rgb(card.color));
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(card.value, x + 3, y + 17);
  });

  y += 30;

  // ── Mohr-Coulomb diagram ──────────────────────────────────────────────────
  const dH = 68; // diagram box height
  fillRect(margin, y, contentW, dH, "#F8FAFC", "#E2E8F0", 2);

  setFont(7, "bold", "#6366F1");
  doc.text(t.diagramTitle, margin + 4, y + 6);

  // Plot area inside the box
  const px = margin + 14;   // origin x (sigma=0)
  const py = y + dH - 10;   // origin y (tau=0, axis line)
  const pw = contentW - 22; // plot width
  const ph = dH - 18;       // plot height

  // Grid lines
  doc.setDrawColor(...rgb("#6366F1"));
  doc.setLineWidth(0.15);
  for (let gx = 0; gx <= pw; gx += pw / 5) {
    doc.line(px + gx, py - ph, px + gx, py);
  }
  for (let gy = 0; gy <= ph; gy += ph / 3) {
    doc.line(px, py - gy, px + pw, py - gy);
  }

  // Axes
  doc.setDrawColor(...rgb("#475569"));
  doc.setLineWidth(0.5);
  doc.line(px - 2, py, px + pw + 4, py);   // sigma axis
  doc.line(px, py + 3, px, y + 9);          // tau axis

  // Arrows
  doc.setFillColor(...rgb("#475569"));
  doc.triangle(px + pw + 4, py - 1, px + pw + 7, py, px + pw + 4, py + 1, "F");
  doc.triangle(px - 1, y + 9, px, y + 6, px + 1, y + 9, "F");

  // Axis labels
  setFont(7, "normal", "#64748B");
  doc.text("\u03C3 (kPa)", px + pw + 8, py + 1);
  doc.text("\u03C4 (kPa)", px - 1, y + 8, { align: "right" });

  // Tick marks
  setFont(6, "normal", "#94A3B8");
  const tickVals = [50, 100, 150, 200, 250, 300];

  // Calculate scale so largest circle fits in pw
  const phiRad = (data.phi * Math.PI) / 180;
  const c = data.cohesion;
  const sigma3s = [20, 70, 150];
  const s1Max = (150 * (1 + Math.sin(phiRad)) + 2 * c * Math.cos(phiRad)) / (1 - Math.sin(phiRad));
  const sc = (pw - 5) / s1Max; // scale: mm per kPa

  tickVals.forEach(sv => {
    const tx = px + sv * sc;
    if (tx < px + pw) {
      doc.setDrawColor(...rgb("#CBD5E1"));
      doc.setLineWidth(0.2);
      doc.line(tx, py, tx, py + 1.5);
      setFont(5, "normal", "#94A3B8");
      doc.text(String(sv), tx, py + 3.5, { align: "center" });
    }
  });

  const tauTicks = [20, 40, 60, 80];
  tauTicks.forEach(tv => {
    const ty = py - tv * sc;
    if (ty > y + 9) {
      doc.setDrawColor(...rgb("#CBD5E1"));
      doc.setLineWidth(0.2);
      doc.line(px - 1.5, ty, px, ty);
      setFont(5, "normal", "#94A3B8");
      doc.text(String(tv), px - 2, ty + 1, { align: "right" });
    }
  });

  // Failure envelope: tau = c + sigma*tan(phi)
  // from (0, c*sc) to clipped at plot boundary
  const envX1 = px;
  const envY1 = py - c * sc;
  // Find where envelope exits plot (either x or y boundary)
  const sigmaAtTopEdge = (ph - c * sc) / (Math.tan(phiRad) * sc);
  const sigmaAtRightEdge = pw / sc;
  const sigmaEnd = Math.min(sigmaAtTopEdge, sigmaAtRightEdge) * 0.95;
  const envX2 = px + sigmaEnd * sc;
  const envY2 = py - (c + sigmaEnd * Math.tan(phiRad)) * sc;

  doc.setDrawColor(...rgb("#6366F1"));
  doc.setLineWidth(0.6);
  doc.setLineDashPattern([1.2, 0.8], 0);
  doc.line(envX1, envY1, envX2, envY2);
  doc.setLineDashPattern([], 0);

  // c intercept dot
  doc.setFillColor(...rgb("#6366F1"));
  doc.circle(px, envY1, 0.8, "F");
  setFont(5.5, "normal", "#F59E0B");
  doc.text(`c = ${c} kPa`, px + 1.5, envY1 - 1);

  // φ label near end of envelope
  setFont(7, "bold", "#F59E0B");
  doc.text(`\u03C6 = ${data.phi}\xB0`, envX2 - 2, envY2 - 2, { align: "right" });

  // Draw Mohr SEMI-circles using bezier approximation
  // k = 0.5523 * r is the bezier control point offset for a circle
  const circleStyles = [
    { color: "#6366F1", opacity: 0.5,  lw: 0.4 },
    { color: "#6366F1", opacity: 0.75, lw: 0.5 },
    { color: "#F59E0B", opacity: 1.0,  lw: 0.7 },
  ];

  sigma3s.forEach((s3, i) => {
    const s1 = (s3 * (1 + Math.sin(phiRad)) + 2 * c * Math.cos(phiRad)) / (1 - Math.sin(phiRad));
    const cxMm = px + ((s1 + s3) / 2) * sc;  // center x in mm
    const rMm  = ((s1 - s3) / 2) * sc;        // radius in mm

    // Skip if circle goes out of bounds
    if (cxMm + rMm > px + pw + 2) return;

    const style = circleStyles[i];
    doc.setDrawColor(...rgb(style.color));
    doc.setLineWidth(style.lw);

    // Upper semicircle using 2 bezier curves
    // L=(cx-r, cy), T=(cx, cy-r), R=(cx+r, cy)
    // k = 0.5523 * r
    const k = 0.5523 * rMm;
    const lx = cxMm - rMm, ly = py;
    const tx = cxMm,       ty = py - rMm;
    const rx = cxMm + rMm, ry = py;

    // Segment L->T: cp1=(lx, ly-k), cp2=(tx-k, ty), end=(tx, ty)
    // Segment T->R: cp1=(tx+k, ty), cp2=(rx, ry-k), end=(rx, ry)
    doc.lines(
      [
        // relative coords from start point
        [0, -k, tx - k - lx, ty - ly, tx - lx, ty - ly],
        [k,  0, rx - tx,     ry - ty - k + k, rx - tx, ry - ty],
      ],
      lx, ly,
      [1, 1],
      undefined,
      false
    );
  });

  y += dH + 8;

  // ── Input parameters ──────────────────────────────────────────────────────
  setFont(11, "bold", "#0F1117");
  doc.text(t.params, margin, y);
  y += 7;

  const paramKeys = ["FC", "WL", "IP", "MC", "SR", "ROD"] as const;
  const units = { FC: "%", WL: "%", IP: "%", MC: "%", SR: "%", ROD: "-" };
  const colW2 = (contentW - 3) / 2;

  paramKeys.forEach((key, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = margin + col * (colW2 + 3);
    const rowY = y + row * 12;

    fillRect(x, rowY, colW2, 10, col === 0 ? "#F8FAFC" : "#FFFFFF", "#E2E8F0", 1);
    setFont(7, "normal", "#64748B");
    doc.text(t[key], x + 3, rowY + 4.5);
    setFont(8, "bold", "#0F1117");
    doc.text(`${data.inputs[key]} ${units[key]}`, x + colW2 - 3, rowY + 4.5, { align: "right" });
  });

  y += Math.ceil(paramKeys.length / 2) * 12 + 8;

  // ── Disclaimer ────────────────────────────────────────────────────────────
  fillRect(margin, y, contentW, 14, "#FEF3C7", "#FCD34D", 2);
  setFont(7, "normal", "#92400E");
  const lines = doc.splitTextToSize(t.disclaimer, contentW - 8);
  doc.text(lines, margin + 4, y + 5);

  // ── Footer ────────────────────────────────────────────────────────────────
  doc.setFillColor(...rgb("#0F1117"));
  doc.rect(0, 285, W, 12, "F");
  setFont(7, "normal", "#64748B");
  doc.text(t.footer, W / 2, 292, { align: "center" });
  setFont(7, "normal", "#475569");
  doc.text("1 / 1", W - margin, 292, { align: "right" });

  // Save
  const filename = `GeoSmartX_${data.soilLabel}_${data.testType.toUpperCase()}_${now.getFullYear()}${String(now.getMonth()+1).padStart(2,"0")}${String(now.getDate()).padStart(2,"0")}.pdf`;
  doc.save(filename);
}